//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramClubWelcomeBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelegramClubWelcomeBot.Resources.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Group welcomes can only be added from the group chat..
        /// </summary>
        internal static string AddWelcomeMustBeGroup {
            get {
                return ResourceManager.GetString("AddWelcomeMustBeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Only the group owner can add welcomes..
        /// </summary>
        internal static string AddWelcomeOwnerOnly {
            get {
                return ResourceManager.GetString("AddWelcomeOwnerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add welcome.
        /// </summary>
        internal static string BotCommandAddWelcome {
            get {
                return ResourceManager.GetString("BotCommandAddWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel welcome adding operation.
        /// </summary>
        internal static string BotCommandCancel {
            get {
                return ResourceManager.GetString("BotCommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😲 Error: sender information is unavailable..
        /// </summary>
        internal static string ErrorMessageFromIsNull {
            get {
                return ResourceManager.GetString("ErrorMessageFromIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Invalid URL..
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Name already exists.
        /// </summary>
        internal static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📎 Send URL or file.
        /// </summary>
        internal static string SendMedia {
            get {
                return ResourceManager.GetString("SendMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💬 Send welcome message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏷 Send welcome name.
        /// </summary>
        internal static string SendWelcomeName {
            get {
                return ResourceManager.GetString("SendWelcomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ Unsupported URL media type..
        /// </summary>
        internal static string UnsupportedUrlMediaType {
            get {
                return ResourceManager.GetString("UnsupportedUrlMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Welcome created.
        /// </summary>
        internal static string WelcomeCreated {
            get {
                return ResourceManager.GetString("WelcomeCreated", resourceCulture);
            }
        }
    }
}
